version: "3"

services:
  mssql:
    container_name: sql-server-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: JumpMan123#
      ACCEPT_EULA: Y
      SQL_SERVER_AGENT_ENABLED: "true"
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql


volumes:
  mssql_data: