---
- name: Deploy Podman Resources (Volumes & Containers) with Quadlet
  hosts: all
  become: true

  tasks:
    - name: Create Quadlet files for volumes
      containers.podman.podman_volume:
        state: quadlet
        name: "{{ item.name }}"
        quadlet_file_mode: '0640'
        quadlet_options: "{{ item.options | default([]) }}"
      loop: "{{ podman_volumes }}"
      loop_control:
        label: "{{ item.name }}"

    # - name: Start Podman volume services
    #   command: systemctl start "{{ item.name }}-volume.service"
    #   ignore_errors: true
    #   loop: "{{ podman_volumes }}"

    # - name: Reload systemd to recognize Quadlet services
    #   command: systemctl daemon-reload

    - name: Create Quadlet files for containers
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: quadlet
        quadlet_file_mode: '0640'
        env: "{{ item.env | default({}) }}"
        ports: "{{ item.ports | default([]) }}"
        volumes: "{{ item.volumes | default([]) }}"
        quadlet_options: "{{ item.options | default([]) }}"
      loop: "{{ podman_containers }}"
      loop_control:
        label: "{{ item.name }}"




    - name: Start Podman container services
      command: systemctl start "{{ item.name }}.service"
      ignore_errors: true
      loop: "{{ podman_containers }}"

    - name: Reload systemd to recognize Quadlet services
      command: systemctl daemon-reload