---
- name: Destroy Podman Resources (Volumes & Containers)
  hosts: all
  become: true

  tasks:
    - name: Stop and disable container services
      command: systemctl stop "{{ item.name }}.service"
      ignore_errors: true
      loop: "{{ podman_containers }}"

    - name: Disable container services
      command: systemctl disable "{{ item.name }}.service"
      ignore_errors: true
      loop: "{{ podman_containers }}"

    - name: Stop and disable volume services
      command: systemctl stop "{{ item.name }}-volume.service"
      ignore_errors: true
      loop: "{{ podman_volumes }}"

    - name: Disable volume services
      command: systemctl disable "{{ item.name }}-volume.service"
      ignore_errors: true
      loop: "{{ podman_volumes }}"

    - name: Delete Quadlet container definition files
      file:
        path: "/etc/containers/systemd/{{ item.filename | default(item.name) }}.container"
        state: absent
      loop: "{{ podman_containers }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Delete Quadlet volume definition files
      file:
        path: "/etc/containers/systemd/{{ item.filename | default(item.name) }}.volume"
        state: absent
      loop: "{{ podman_volumes }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Remove generated systemd service files for containers
      file:
        path: "/run/systemd/generator/{{ item.name }}.service"
        state: absent
      loop: "{{ podman_containers }}"
      ignore_errors: true

    - name: Remove generated systemd service files for volumes
      file:
        path: "/run/systemd/generator/{{ item.filename }}-volume.service"
        state: absent
      loop: "{{ podman_volumes }}"
      ignore_errors: true

    - name: Delete Podman volumes
      command: podman volume rm "{{ item.filename }}"
      ignore_errors: true
      loop: "{{ podman_volumes }}"

    - name: Ensure all volume-related systemd files are deleted
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/containers/systemd/{{ podman_volumes | map(attribute='filename') | join('.volume,') }}.volume"
        - "/run/systemd/generator/{{ podman_volumes | map(attribute='filename') | join('-volume.service,') }}-volume.service"
      ignore_errors: true

    - name: delete volumes manually
      command: rm -rf /var/lib/containers/storage/volumes/{{ item.name }}
      loop: "{{ podman_volumes }}"
      ignore_errors: true

    - name: Reload systemd to clear deleted services
      command: systemctl daemon-reload
