---
- name: Update system and install Podman packages
  hosts: all
  become: false

  tasks:
    - name: Ensure dnf is up-to-date
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      become: true

    - name: Install required DNF packages
      dnf:
        name: "{{ dnf_packages }}"
        state: present
      become: true
    
    - name: Ensure pip3 is installed
      dnf:
        name: python3-pip
        state: present
      become: true

    - name: Install podman-compose using pip3
      pip:
        name: podman-compose
        state: present
        executable: pip3
      become: true
